// <auto-generated />
namespace Final_Moviles.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class commitdos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commitdos));
        
        string IMigrationMetadata.Id
        {
            get { return "201811280429373_commitdos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
